In [181]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [182]:
##load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

RowNumber	CustomerId	Surname are not as such important

In [183]:
#preprocessing the data
#Drop irrelevant columns
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)#axis=1 means column wise
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

in column geography and gender are catagorical varible

In [184]:
##Encode one catagorical variable
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

LabelEncoder is a class from scikit-learn used to convert categorical text values into numbers.

In [185]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [186]:
##one hot encoding for geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [187]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [188]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [189]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [190]:
#Combine One hot encoder columns with the orignal data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [191]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [192]:
##save the encoders and scalers
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb')as file:
    pickle.dump(onehot_encoder_geo,file)

In [193]:
##Devide the dataset into dependent and independent features
X=data.drop('Exited',axis=1)
y=data['Exited']

In [194]:
#split the data in training and testing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#Scale these features\
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [195]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [196]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [197]:
with open ('scaler.pkl','wb')as file:
    pickle.dump(scaler,file)

In [198]:
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

ANN implimentation

In [199]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [200]:
(X_train.shape[1],)

(12,)

In [201]:
#building ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),#HL2
    Dense(1,activation='sigmoid')##op layer
])

In [202]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_15 (Dense)            (None, 64)                832

 dense_16 (Dense)            (None, 32)                2080

 dense_17 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [203]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [204]:
##compile the model
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [205]:
#setup the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard


log_dir="logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [206]:
#setup earlystopping

early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [207]:
#train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4583 - accuracy: 0.8015 - val_loss: 0.3962 - val_accuracy: 0.8265
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3883 - accuracy: 0.8416 - val_loss: 0.3569 - val_accuracy: 0.8515
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3570 - accuracy: 0.8539 - val_loss: 0.3477 - val_accuracy: 0.8585
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3430 - accuracy: 0.8570 - val_loss: 0.3471 - val_accuracy: 0.8585
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8593 - val_loss: 0.3429 - val_accuracy: 0.8600
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8591 - val_loss: 0.3428 - val_accuracy: 0.8655
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8634 - val_loss: 0.3447 - val_accuracy: 0.8565
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3280 - accuracy: 0.8648 - val_loss: 0.3432 - val_accuracy: 0.8590
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8674 - val_loss: 0.3428 - val_accuracy: 0.8635
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8649 - val_loss: 0.3377 - val_accuracy: 0.8630
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3217 - accuracy: 0.8664 - val_loss: 0.3395 - val_accuracy: 0.8625
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3200 - accuracy: 0.8658 - val_loss: 0.3396 - val_accuracy: 0.8615
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3177 - accuracy: 0.8676 - val_loss: 0.3385 - val_accuracy: 0.8615
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3174 - accuracy: 0.8655 - val_loss: 0.3437 - val_accuracy: 0.8590
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3154 - accuracy: 0.8674 - val_loss: 0.3409 - val_accuracy: 0.8570
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3134 - accuracy: 0.8683 - val_loss: 0.3478 - val_accuracy: 0.8555
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3120 - accuracy: 0.8699 - val_loss: 0.3371 - val_accuracy: 0.8660
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3116 - accuracy: 0.8683 - val_loss: 0.3373 - val_accuracy: 0.8635
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3108 - accuracy: 0.8681 - val_loss: 0.3357 - val_accuracy: 0.8625
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3068 - accuracy: 0.8714 - val_loss: 0.3420 - val_accuracy: 0.8580
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3080 - accuracy: 0.8706 - val_loss: 0.3393 - val_accuracy: 0.8615
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3056 - accuracy: 0.8720 - val_loss: 0.3496 - val_accuracy: 0.8545
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.8723 - val_loss: 0.3474 - val_accuracy: 0.8545
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3044 - accuracy: 0.8721 - val_loss: 0.3412 - val_accuracy: 0.8610
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.8720 - val_loss: 0.3433 - val_accuracy: 0.8605
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3018 - accuracy: 0.8735 - val_loss: 0.3421 - val_accuracy: 0.8600
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3020 - accuracy: 0.8719 - val_loss: 0.3425 - val_accuracy: 0.8665
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8737 - val_loss: 0.3417 - val_accuracy: 0.8610
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 0.2984 - accuracy: 0.8744 - val_loss: 0.3452 - val_accuracy: 0.8595

In [208]:
model.save('model.h5')

e:\ANN Classification\churn_venv2\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [209]:
#load tensorboad extensiom


%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [210]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 6452), started 0:14:48 ago. (Use '!kill 6452' to kill it.)